#Numpy tutorial

##What is NumPy?
👉 NumPy is a Python library for working with numbers and data in the form of arrays (like supercharged lists). It makes math, statistics, and data manipulation fast and easy, and it’s the foundation for most data science and AI libraries.

##Why Use NumPy?

It’s much faster than Python lists for math and data operations (because it uses optimized C code under the hood).

It provides powerful tools like multidimensional arrays, vectorized operations, linear algebra, statistics, and random number generation.

It’s the foundation of data science and AI libraries (like pandas, scikit-learn, TensorFlow, PyTorch).

⚡ Example: Adding two lists in Python vs NumPy:




In [2]:
# With Python lists
a = [1, 2, 3]
b = [4, 5, 6]
result = [a[i] + b[i] for i in range(len(a))]  # [5, 7, 9]

# With NumPy
import numpy as np
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
result = a + b   # [5 7 9]
print(result)


[5 7 9]


##Why is NumPy Faster Than Lists?
👉Stores data in one continuous block of memory.

👉Uses fixed data types (less overhead).

👉Runs vectorized operations in optimized C code (no Python loops).

In [ ]:
import numpy as np
a, b = np.arange(1_000_000), np.arange(1_000_000)
print("List:", sum([i+j for i,j in zip(range(1_000_000), range(1_000_000))]))
print("NumPy:", sum(a + b))
#👉 NumPy runs much faster than lists.

#Arrays in numpy

##Create a NumPy ndarray Object
An ndarray is the main data structure in NumPy (n-dimensional array).

You can create it using np.array() from a Python list or tuple.

In [ ]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5])
print(arr)           # [1 2 3 4 5]
print(type(arr))     # <class 'numpy.ndarray'>


##Dimensions in Arrays
👉 The number of dimensions (also called axes or rank) tells us how many directions the data is organized in.

###1. 0-D Array (Scalar)
Contains a single value.

In [3]:
import numpy as np
arr = np.array(42)
print(arr)        # 42
print(arr.ndim)   # 0


42
0


###2. 1-D Array (Vector)
Contains values in a single row (like a list).

In [3]:
import numpy as np
arr = np.array([1, 2, 3, 4, 5])
print(arr)        # [1 2 3 4 5]
print(arr.ndim)   # 1


[1 2 3 4 5]
1


###3. 2-D Array (Matrix)
Rows and columns (like a table).

In [3]:
import numpy as np
arr = np.array([[1, 2, 3], [4, 5, 6]])
print(arr)
# [[1 2 3]
#  [4 5 6]]
print(arr.ndim)   # 2


[[1 2 3]
 [4 5 6]]
2


###4. 3-D Array (Tensor)

Array inside an array of matrices.

In [2]:
import numpy as np
arr = np.array([ [[1, 2, 3], [4, 5, 6]],
                 [[7, 8, 9], [10, 11, 12]] ])
print(arr.ndim)   # 3


3


###5. Higher Dimensions (n-D Arrays)

NumPy can handle arrays with any number of dimensions.

In [4]:
arr = np.array([1, 2, 3, 4], ndmin=5)
print(arr)        # [[[[[1 2 3 4]]]]]
print(arr.ndim)   # 5


[[[[[1 2 3 4]]]]]
5


##Accessing Array Elements in NumPy
👉 Just like Python lists, you can use indexing to access elements in a NumPy array.

Indexing starts at 0 (first element).

You can also use negative indexing (from the end).

###1. Access elements in a 1-D array

In [ ]:
import numpy as np

arr = np.array([10, 20, 30, 40])

print(arr[0])   # 10 (first element)
print(arr[2])   # 30 (third element)
print(arr[-1])  # 40 (last element)


###2. Access elements in a 2-D array

👉 Use row index, column index.

In [ ]:
arr = np.array([[1, 2, 3], [4, 5, 6]])

print(arr[0, 1])  # 2  (row 0, column 1)
print(arr[1, 2])  # 6  (row 1, column 2)


###3. Access elements in a 3-D array

👉 Use 3 indices: block, row, column.

In [ ]:
arr = np.array([ [[1, 2], [3, 4]], [[5, 6], [7, 8]] ])

print(arr[0, 1, 1])  # 4  (block 0, row 1, column 1)
print(arr[1, 0, 0])  # 5  (block 1, row 0, column 0)


✅ Tip: You can also use slicing (:) to access ranges of elements.