#Numpy tutorial

##What is NumPy?
👉 NumPy is a Python library for working with numbers and data in the form of arrays (like supercharged lists). It makes math, statistics, and data manipulation fast and easy, and it’s the foundation for most data science and AI libraries.

##Why Use NumPy?

It’s much faster than Python lists for math and data operations (because it uses optimized C code under the hood).

It provides powerful tools like multidimensional arrays, vectorized operations, linear algebra, statistics, and random number generation.

It’s the foundation of data science and AI libraries (like pandas, scikit-learn, TensorFlow, PyTorch).

⚡ Example: Adding two lists in Python vs NumPy:




In [ ]:
# With Python lists
a = [1, 2, 3]
b = [4, 5, 6]
result = [a[i] + b[i] for i in range(len(a))]  # [5, 7, 9]

# With NumPy
import numpy as np
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
result = a + b   # [5 7 9]
print(result)


[5 7 9]


##Why is NumPy Faster Than Lists?
👉Stores data in one continuous block of memory.

👉Uses fixed data types (less overhead).

👉Runs vectorized operations in optimized C code (no Python loops).

In [ ]:
import numpy as np
a, b = np.arange(1_000_000), np.arange(1_000_000)
print("List:", sum([i+j for i,j in zip(range(1_000_000), range(1_000_000))]))
print("NumPy:", sum(a + b))
#👉 NumPy runs much faster than lists.

#Arrays in numpy

##Create a NumPy ndarray Object
An ndarray is the main data structure in NumPy (n-dimensional array).

You can create it using np.array() from a Python list or tuple.

In [ ]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5])
print(arr)           # [1 2 3 4 5]
print(type(arr))     # <class 'numpy.ndarray'>


##Dimensions in Arrays
👉 The number of dimensions (also called axes or rank) tells us how many directions the data is organized in.

###1. 0-D Array (Scalar)
Contains a single value.

In [ ]:
import numpy as np
arr = np.array(42)
print(arr)        # 42
print(arr.ndim)   # 0


42
0


###2. 1-D Array (Vector)
Contains values in a single row (like a list).

In [ ]:
import numpy as np
arr = np.array([1, 2, 3, 4, 5])
print(arr)        # [1 2 3 4 5]
print(arr.ndim)   # 1


[1 2 3 4 5]
1


###3. 2-D Array (Matrix)
Rows and columns (like a table).

In [ ]:
import numpy as np
arr = np.array([[1, 2, 3], [4, 5, 6]])
print(arr)
# [[1 2 3]
#  [4 5 6]]
print(arr.ndim)   # 2


[[1 2 3]
 [4 5 6]]
2


###4. 3-D Array (Tensor)

Array inside an array of matrices.

In [ ]:
import numpy as np
arr = np.array([ [[1, 2, 3], [4, 5, 6]],
                 [[7, 8, 9], [10, 11, 12]] ])
print(arr.ndim)   # 3


3


###5. Higher Dimensions (n-D Arrays)

NumPy can handle arrays with any number of dimensions.

In [ ]:
arr = np.array([1, 2, 3, 4], ndmin=5)
print(arr)        # [[[[[1 2 3 4]]]]]
print(arr.ndim)   # 5


[[[[[1 2 3 4]]]]]
5


##Accessing Array Elements in NumPy
👉 Just like Python lists, you can use indexing to access elements in a NumPy array.

Indexing starts at 0 (first element).

You can also use negative indexing (from the end).

###1. Access elements in a 1-D array

In [ ]:
import numpy as np

arr = np.array([10, 20, 30, 40])

print(arr[0])   # 10 (first element)
print(arr[2])   # 30 (third element)
print(arr[-1])  # 40 (last element)


###2. Access elements in a 2-D array

👉 Use row index, column index.

In [ ]:
import numpy as np
arr = np.array([[1, 2, 3], [4, 5, 6]])

print(arr[0, 1])  # 2  (row 0, column 1)
print(arr[1, 2])  # 6  (row 1, column 2)


###3. Access elements in a 3-D array

👉 Use 3 indices: block, row, column.

In [ ]:
import numpy as np
arr = np.array([ [[1, 2], [3, 4]], [[5, 6], [7, 8]] ])

print(arr[0, 1, 1])  # 4  (block 0, row 1, column 1)
print(arr[1, 0, 0])  # 5  (block 1, row 0, column 0)


4
5


✅ Tip: You can also use slicing (:) to access ranges of elements.

#NumPy Array Slicing

Slicing allows you to select parts of an array without modifying the original.
The syntax:
array[start:stop:step]

👉 start → starting index (inclusive, default 0)

👉 stop → ending index (exclusive)

👉 step → step size between indices (default 1)

##1️⃣ Slicing 1D Arrays

In [ ]:
import numpy as np

arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

# Elements from index 2 to 5 (5 excluded)
print(arr[2:5])   # Output: [2 3 4]

# Every second element
print(arr[::2])   # Output: [0 2 4 6 8]

# Last three elements
print(arr[-3:])   # Output: [7 8 9]


##2️⃣ Slicing 2D Arrays

In [ ]:
arr2d = np.array([[1, 2, 3],
                  [4, 5, 6],
                  [7, 8, 9]])

# First row
print(arr2d[0, :])   # Output: [1 2 3]

# Second column
print(arr2d[:, 1])   # Output: [2 5 8]

# Submatrix (rows 0-1, columns 1-2)
print(arr2d[0:2, 1:3])
# Output:
# [[2 3]
#  [5 6]]


##🔹 Negative Indices in NumPy

In Python/NumPy, negative indices count from the end of the array instead of the beginning:

-1 → last element

-2 → second-to-last element

-3 → third-to-last element, and so on

In [ ]:
import numpy as np

arr = np.array([10, 20, 30, 40, 50])

print(arr[-1])   # Output: 50 (last element)
print(arr[-3])   # Output: 30 (third-to-last element)

# Slicing with negative indices
print(arr[-4:-1])  # Output: [20 30 40] (from index -4 to -2)


##🔹 Step (Stride) in Slicing

The step (or stride) determines how many elements to skip between selections. It’s the third value in the slice:

array[start:stop:step]


step = 1 → default, select every element

step = 2 → select every second element

step = -1 → reverse the array

In [ ]:
arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

# Every 2nd element
print(arr[::2])    # Output: [0 2 4 6 8]

# Reverse the array
print(arr[::-1])   # Output: [9 8 7 6 5 4 3 2 1 0]

# Reverse a slice (last 5 elements in reverse)
print(arr[-1:-6:-1])  # Output: [9 8 7 6 5]


##NumPy Data Types
###Data Types in Python
By default Python have these data types:

strings - used to represent text data, the text is given under quote marks. e.g. "ABCD"

integer - used to represent integer numbers. e.g. -1, -2, -3

float - used to represent real numbers. e.g. 1.2, 42.42

boolean - used to represent True or False.

complex - used to represent complex numbers. e.g. 1.0 + 2.0j, 1.5 + 2.5j

###Data Types in NumPy
NumPy has some extra data types, and refer to data types with one character, like i for integers, u for unsigned integers etc.

Below is a list of all data types in NumPy and the characters used to represent them.

i - integer

b - boolean

u - unsigned integer

f - float

c - complex float

m - timedelta

M - datetime

O - object

S - string

U - unicode string

V - fixed chunk of memory for other type ( void )

In [ ]:
import numpy as np

arr_int = np.array([1, 2, 3], dtype='i')
arr_float = np.array([1.0, 2.0, 3.0], dtype='f')
arr_bool = np.array([0, 1, 0], dtype='b')

print(arr_int, arr_int.dtype)    # Output: [1 2 3] int32 (or int64)
print(arr_float, arr_float.dtype)  # Output: [1. 2. 3.] float32 (or float64)
print(arr_bool, arr_bool.dtype)    # Output: [False  True False] bool


##NumPy Array: Copy vs View

In NumPy, when you manipulate arrays, it’s important to understand whether you are creating a new independent array (copy) or just a view of the same data (view).

In [ ]:
import numpy as np

arr = np.array([1, 2, 3, 4])
view_arr = arr.view()  # create a view

view_arr[0] = 100
print(arr)       # Output: [100   2   3   4] → original array changed
print(view_arr)  # Output: [100   2   3   4]


##2️ Copy

A copy is a new array with its own data.

Changes in the copy do NOT affect the original array.

Memory is allocated separately.

In [3]:
copy_arr = arr.copy()  # create a copy

copy_arr[1] = 200
print(arr)       # Output: [100   2   3   4] → original stays same
print(copy_arr)  # Output: [100 200   3   4] → only copy changed


[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]
[[[  1   2]
  [  3   4]]

 [[200 200]
  [200 200]]]


##NumPy Array Shape

The shape of a NumPy array tells you how many elements are along each dimension.

👉Use the .shape attribute to check the shape of an array.

👉For a 2D array, .shape returns (rows, columns)

👉For a 3D array, .shape returns (depth, rows, columns)

xample with 1D Array

### Example with 1D Array

In [ ]:
import numpy as np

arr1d = np.array([1, 2, 3, 4, 5])
print(arr1d.shape)  # Output: (5,) → 1D array with 5 elements


##Example with 2D Array

In [ ]:
import numpy as np
arr2d = np.array([[1, 2, 3],
                  [4, 5, 6]])
print(arr2d.shape)  # Output: (2, 3) → 2 rows, 3 columns


### Example with 3D Array

In [1]:
import numpy as np
arr3d = np.array([[[1, 2], [3, 4]],
                  [[5, 6], [7, 8]]])
print(arr3d.shape)  # Output: (2, 2, 2) → 2 blocks, 2 rows, 2 columns


(2, 2, 2)


### Reshaping Arrays

In [2]:
import numpy as np
arr = np.array([1, 2, 3, 4, 5, 6])
reshaped = arr.reshape(2, 3)  # 2 rows, 3 columns
print(reshaped)
# Output:
# [[1 2 3]
#  [4 5 6]]


[[1 2 3]
 [4 5 6]]


## Iterating over NumPy Arrays

Sometimes you need to go through each element in a NumPy array. You can iterate over arrays using loops or special NumPy functions.

###1 Iterating over 1D Arrays


In [ ]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5])

for x in arr:
    print(x)

##2 Iterating over 2D Arrays (row by row)










In [ ]:
arr2d = np.array([[1, 2, 3],
                  [4, 5, 6]])

for row in arr2d:
    print(row)

##3 Iterating over each element in 2D Arrays

In [3]:
import numpy as np

arr2d = np.array([[1, 2, 3],
                  [4, 5, 6]])
for row in arr2d:
    for elem in row:
        print(elem)

1
2
3
4
5
6


##4 Using nditer() for n-dimensional arrays

nditer() lets you iterate over every element in an n-dimensional array easily:


In [ ]:

arr3d = np.array([[[1, 2], [3, 4]],
                  [[5, 6], [7, 8]]])

for x in np.nditer(arr3d):
    print(x)

✅ Tips

For 1D arrays, simple for x in arr works fine.

For multi-dimensional arrays, you can use nested loops or np.nditer() for cleaner code.

Iterating is slower than vectorized operations, but it’s useful for element-wise operations that aren’t easy with NumPy functions.

##🟢 Joining NumPy Arrays

In NumPy, you can join (combine) two or more arrays into a single array.
This is done mainly using concatenate(), stack(), and their variations.

###1 Using concatenate()

The np.concatenate() function joins arrays along an existing axis.

In [ ]:
import numpy as np

arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])

joined = np.concatenate((arr1, arr2))
print(joined)


###For 2D arrays (joining along rows and columns):

In [5]:
arr1 = np.array([[1, 2], [3, 4]])
arr2 = np.array([[5, 6], [7, 8]])

# Join along axis 0 (rows)
joined_axis0 = np.concatenate((arr1, arr2), axis=0)

# Join along axis 1 (columns)
joined_axis1 = np.concatenate((arr1, arr2), axis=1)

print(joined_axis0)
# [[1 2]
#  [3 4]
#  [5 6]
#  [7 8]]

print(joined_axis1)
# [[1 2 5 6]
#  [3 4 7 8]]


[[1 2]
 [3 4]
 [5 6]
 [7 8]]
[[1 2 5 6]
 [3 4 7 8]]


###2 Using stack()

The np.stack() function joins arrays along a new axis.

In [4]:
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])

stacked = np.stack((arr1, arr2), axis=0)
print(stacked)


[[1 2 3]
 [4 5 6]]


###3 Other Stacking Methods

hstack() → Stacks arrays horizontally (along columns).

vstack() → Stacks arrays vertically (along rows).

dstack() → Stacks arrays along depth (3rd dimension).

In [ ]:
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])

print(np.hstack((arr1, arr2)))  # [1 2 3 4 5 6]
print(np.vstack((arr1, arr2)))
# [[1 2 3]
#  [4 5 6]]
print(np.dstack((arr1, arr2)))
# [[[1 4]
#   [2 5]
#   [3 6]]]


✅ Key Points:

Use concatenate() to join along existing axes.

Use stack() (or hstack, vstack, dstack) to create a new axis.

Choose the method based on whether you want to expand dimensions or not.

## Splitting NumPy Arrays

The opposite of joining arrays is splitting them into multiple arrays.
NumPy provides functions like array_split(), hsplit(), vsplit(), and dsplit().

### Using array_split()

You can split an array into multiple sub-arrays.

In [ ]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6])

splitted = np.array_split(arr, 3)
print(splitted)


👉 Notice: array_split() works even if the array cannot be divided equally.

In [ ]:
arr = np.array([1, 2, 3, 4, 5, 6, 7])

splitted = np.array_split(arr, 3)
print(splitted)


###2 Splitting 2D Arrays

In [6]:
arr2d = np.array([[1, 2],
                  [3, 4],
                  [5, 6],
                  [7, 8]])

# Split into 2 parts along rows (axis=0)
split_rows = np.array_split(arr2d, 2, axis=0)

# Split into 2 parts along columns (axis=1)
split_cols = np.array_split(arr2d, 2, axis=1)

print(split_rows)
print(split_cols)


[array([[1, 2],
       [3, 4]]), array([[5, 6],
       [7, 8]])]
[array([[1],
       [3],
       [5],
       [7]]), array([[2],
       [4],
       [6],
       [8]])]


###3 Using hsplit(), vsplit(), and dsplit()

hsplit() → Split along columns (horizontally).

vsplit() → Split along rows (vertically).

dsplit() → Split along depth (3rd dimension).

In [ ]:
arr = np.array([[1, 2, 3, 4],
                [5, 6, 7, 8]])

print(np.hsplit(arr, 2))  # split into 2 parts by columns
print(np.vsplit(arr, 2))  # split into 2 parts by rows


✅ Key Points:

Use array_split() when you want flexibility (uneven splits allowed).

Use hsplit, vsplit, dsplit for clean splitting along fixed axes.

Splitting is often used in data preprocessing (e.g., train/test datasets).

## NumPy Searching Arrays

Searching means finding elements in an array that match certain conditions.
NumPy provides helpful functions like where() and searchsorted().

###1 Using where()

The np.where() function returns the indices of elements that match a condition.

In [1]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 4, 6])

# Find all indices where value = 4
indices = np.where(arr == 4)
print(indices)


(array([3, 5]),)


👉 You can also use conditions:

In [ ]:
print(np.where(arr > 3))  # elements greater than 3


###2 Using searchsorted()

The np.searchsorted() function tells you where a value should be inserted in a sorted array to keep it sorted.

In [ ]:
arr = np.array([1, 3, 5, 7])

pos = np.searchsorted(arr, 4)
print(pos)  # Output: 2 → 4 should be placed at index 2


👉 For multiple values:

In [ ]:
print(np.searchsorted(arr, [2, 6]))


###3 Combining with Boolean Indexing

You can also directly filter elements using conditions:

In [ ]:
arr = np.array([10, 15, 20, 25, 30])

print(arr[arr > 20])  # Output: [25 30]


In [ ]:
arr = np.array([10, 15, 20, 25, 30])

print(arr[arr > 20])  # Output: [25 30]


✅ Key Points:

where() → returns indices of elements matching a condition.

searchsorted() → finds insertion index in sorted arrays.

Boolean indexing → directly extracts elements.

##NumPy Sorting Arrays

Sorting means arranging elements in ascending or descending order.
NumPy provides the function np.sort() to handle sorting easily.

###1 Sorting 1D Arrays

In [2]:
import numpy as np

arr = np.array([3, 1, 5, 2, 4])

print(np.sort(arr))


[1 2 3 4 5]


###2 Sorting 2D Arrays

You can sort a 2D array row-wise or column-wise.

In [3]:
arr = np.array([[3, 2, 4], [5, 1, 7]])

print(np.sort(arr))   # sorts each row


[[2 3 4]
 [1 5 7]]


###3 Sorting Strings

Sorting also works for strings alphabetically:

In [ ]:
arr = np.array(['banana', 'apple', 'cherry'])
print(np.sort(arr))


###4 In-Place Sorting with .sort()

If you want to sort an array directly (without creating a new one):

In [ ]:
arr = np.array([3, 1, 4, 2])
arr.sort()
print(arr)


✅ Key Points:

Use np.sort() → returns a sorted copy.

Use .sort() → sorts the original array in-place.

Works with numbers, strings, and even multi-dimensional arrays.

## NumPy Filter Array

Filtering means selecting elements from an array that satisfy a condition.
This is done using boolean indexing: you create a boolean array (True/False values) and use it to filter the original array.

###✅ Example 1: Filter Even Numbers

In [ ]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6])

# Create a filter (True if number is even)
filter_arr = arr % 2 == 0

print("Filter:", filter_arr)

# Apply filter
new_arr = arr[filter_arr]

print("Filtered array:", new_arr)


###✅ Example 2: Filter Values Greater Than 3

In [ ]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6])

filter_arr = arr > 3

new_arr = arr[filter_arr]

print("Filtered array:", new_arr)


###✅ Example 3: Manual Custom Filter

You can even build the filter manually:

In [ ]:
import numpy as np

arr = np.array([10, 20, 30, 40])

# Keep only values equal to 20
filter_arr = [value == 20 for value in arr]

new_arr = arr[filter_arr]

print("Filtered array:", new_arr)


⚡ Key Point:

arr[condition] returns only the elements where the condition is True.

This is much faster and shorter than writing loops.